/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class WotdEntrySchema extends BaseModel {
  static $columns = ['createdAt', 'date', 'definition', 'etymology', 'exampleSentence', 'id', 'partOfSpeech', 'pronunciation', 'updatedAt', 'word'] as const
  $columns = WotdEntrySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare date: DateTime
  @column()
  declare definition: string
  @column()
  declare etymology: string
  @column()
  declare exampleSentence: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare partOfSpeech: string
  @column()
  declare pronunciation: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare word: string
}
